# Generated by Django 5.1 on 2024-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
