# Generated by Django 5.1 on 2024-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_apellido_remove_customuser_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
