# Generated by Django 5.1 on 2024-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
